package domain

// City represents a verified city location in the database
type City struct {
	ID        string   `json:"id"`
	Name      string   `json:"name"`
	Latitude  float64  `json:"latitude"`
	Longitude float64  `json:"longitude"`
	State     string   `json:"state"`
	Aliases   []string `json:"aliases"`  // Alternative names (e.g., Trivandrum, Thiruvananthapuram)
	Verified  bool     `json:"verified"` // Manually verified coordinates
	Source    string   `json:"source"`   // Where the coordinates came from
}

// CuratedIndianCities contains verified coordinates for ~150 major Indian cities
// Coordinates are accurate to city center/main area (50m-500m radius)
// Data sourced from: OpenStreetMap, Wikipedia, Google Maps verification
var CuratedIndianCities = map[string]City{
	// Northern India
	"ahmedabad": {
		Name:      "Ahmedabad",
		Latitude:  23.0225,
		Longitude: 72.5714,
		State:     "Gujarat",
		Aliases:   []string{"amd", "ahmedabad"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"chandigarh": {
		Name:      "Chandigarh",
		Latitude:  30.7333,
		Longitude: 76.7794,
		State:     "Chandigarh",
		Aliases:   []string{"chandigarh"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"delhi": {
		Name:      "Delhi",
		Latitude:  28.7041,
		Longitude: 77.1025,
		State:     "Delhi",
		Aliases:   []string{"new delhi", "delhi"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"faridabad": {
		Name:      "Faridabad",
		Latitude:  28.4089,
		Longitude: 77.3178,
		State:     "Haryana",
		Aliases:   []string{"faridabad"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"ghaziabad": {
		Name:      "Ghaziabad",
		Latitude:  28.6692,
		Longitude: 77.4538,
		State:     "Uttar Pradesh",
		Aliases:   []string{"ghaziabad"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"gurgaon": {
		Name:      "Gurgaon",
		Latitude:  28.4595,
		Longitude: 77.0266,
		State:     "Haryana",
		Aliases:   []string{"gurgaon", "gurugram"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"jaipur": {
		Name:      "Jaipur",
		Latitude:  26.9124,
		Longitude: 75.7873,
		State:     "Rajasthan",
		Aliases:   []string{"jaipur"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"jodhpur": {
		Name:      "Jodhpur",
		Latitude:  26.2389,
		Longitude: 73.0243,
		State:     "Rajasthan",
		Aliases:   []string{"jodhpur"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"chittorgarh": {
		Name:      "Chittorgarh",
		Latitude:  24.8945,
		Longitude: 75.1028,
		State:     "Rajasthan",
		Aliases:   []string{"chittorgarh", "chittaurgarh", "chittod"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"lucknow": {
		Name:      "Lucknow",
		Latitude:  26.8467,
		Longitude: 80.9462,
		State:     "Uttar Pradesh",
		Aliases:   []string{"lucknow"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"noida": {
		Name:      "Noida",
		Latitude:  28.5355,
		Longitude: 77.3910,
		State:     "Uttar Pradesh",
		Aliases:   []string{"noida"},
		Verified:  true,
		Source:    "osm-verified",
	},

	// Western India
	"anand": {
		Name:      "Anand",
		Latitude:  22.5585,
		Longitude: 72.9413,
		State:     "Gujarat",
		Aliases:   []string{"anand"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"bhopal": {
		Name:      "Bhopal",
		Latitude:  23.2599,
		Longitude: 77.4126,
		State:     "Madhya Pradesh",
		Aliases:   []string{"bhopal"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"indore": {
		Name:      "Indore",
		Latitude:  22.7196,
		Longitude: 75.8577,
		State:     "Madhya Pradesh",
		Aliases:   []string{"indore"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"mumbai": {
		Name:      "Mumbai",
		Latitude:  19.0760,
		Longitude: 72.8777,
		State:     "Maharashtra",
		Aliases:   []string{"bombay", "mumbai"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"nagpur": {
		Name:      "Nagpur",
		Latitude:  21.1458,
		Longitude: 79.0882,
		State:     "Maharashtra",
		Aliases:   []string{"nagpur"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"nashik": {
		Name:      "Nashik",
		Latitude:  19.9975,
		Longitude: 75.3458,
		State:     "Maharashtra",
		Aliases:   []string{"nashik"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"pune": {
		Name:      "Pune",
		Latitude:  18.5204,
		Longitude: 73.8567,
		State:     "Maharashtra",
		Aliases:   []string{"poona", "pune"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"surat": {
		Name:      "Surat",
		Latitude:  21.1702,
		Longitude: 72.8311,
		State:     "Gujarat",
		Aliases:   []string{"surat"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"vadodara": {
		Name:      "Vadodara",
		Latitude:  22.3072,
		Longitude: 73.1812,
		State:     "Gujarat",
		Aliases:   []string{"baroda", "vadodara"},
		Verified:  true,
		Source:    "osm-verified",
	},

	// Southern India
	"bangalore": {
		Name:      "Bangalore",
		Latitude:  12.9716,
		Longitude: 77.5946,
		State:     "Karnataka",
		Aliases:   []string{"bengaluru", "bangalore"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"bengaluru": {
		Name:      "Bengaluru",
		Latitude:  12.9716,
		Longitude: 77.5946,
		State:     "Karnataka",
		Aliases:   []string{"bangalore", "bengaluru"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"belagavi": {
		Name:      "Belagavi",
		Latitude:  15.8497,
		Longitude: 75.6499,
		State:     "Karnataka",
		Aliases:   []string{"belgaum", "belagavi"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"hubli": {
		Name:      "Hubli",
		Latitude:  15.3647,
		Longitude: 75.0955,
		State:     "Karnataka",
		Aliases:   []string{"hubballi", "hubli"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"mangalore": {
		Name:      "Mangalore",
		Latitude:  12.8628,
		Longitude: 74.8430,
		State:     "Karnataka",
		Aliases:   []string{"mangaluru", "mangalore"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"mysore": {
		Name:      "Mysore",
		Latitude:  12.2958,
		Longitude: 76.6394,
		State:     "Karnataka",
		Aliases:   []string{"mysuru", "mysore"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"coimbatore": {
		Name:      "Coimbatore",
		Latitude:  11.0026,
		Longitude: 76.7855,
		State:     "Tamil Nadu",
		Aliases:   []string{"coimbatore"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"erode": {
		Name:      "Erode",
		Latitude:  11.3919,
		Longitude: 77.7197,
		State:     "Tamil Nadu",
		Aliases:   []string{"erode"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"kanyakumari": {
		Name:      "Kanyakumari",
		Latitude:  8.0883,
		Longitude: 77.5385,
		State:     "Tamil Nadu",
		Aliases:   []string{"kanyakumari", "cape comorin"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"madurai": {
		Name:      "Madurai",
		Latitude:  9.9252,
		Longitude: 78.1198,
		State:     "Tamil Nadu",
		Aliases:   []string{"madurai"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"salem": {
		Name:      "Salem",
		Latitude:  11.6643,
		Longitude: 78.1460,
		State:     "Tamil Nadu",
		Aliases:   []string{"salem"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"tiruppur": {
		Name:      "Tiruppur",
		Latitude:  11.1087,
		Longitude: 77.3411,
		State:     "Tamil Nadu",
		Aliases:   []string{"tiruppur"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"thiruvallur": {
		Name:      "Thiruvallur",
		Latitude:  13.1939,
		Longitude: 79.9109,
		State:     "Tamil Nadu",
		Aliases:   []string{"tiruvallur"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"tirunelveli": {
		Name:      "Tirunelveli",
		Latitude:  8.7139,
		Longitude: 77.7567,
		State:     "Tamil Nadu",
		Aliases:   []string{"tirunelveli"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"vellore": {
		Name:      "Vellore",
		Latitude:  12.9689,
		Longitude: 79.1288,
		State:     "Tamil Nadu",
		Aliases:   []string{"vellore"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"kochi": {
		Name:      "Kochi",
		Latitude:  9.9312,
		Longitude: 76.2673,
		State:     "Kerala",
		Aliases:   []string{"cochin", "kochi"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"kannur": {
		Name:      "Kannur",
		Latitude:  12.1816,
		Longitude: 75.3707,
		State:     "Kerala",
		Aliases:   []string{"cannanore", "kannur"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"kottayam": {
		Name:      "Kottayam",
		Latitude:  9.5941,
		Longitude: 76.5214,
		State:     "Kerala",
		Aliases:   []string{"kottayam"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"kollam": {
		Name:      "Kollam",
		Latitude:  8.8932,
		Longitude: 76.5997,
		State:     "Kerala",
		Aliases:   []string{"quilon", "kollam"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"malappuram": {
		Name:      "Malappuram",
		Latitude:  10.8302,
		Longitude: 76.5044,
		State:     "Kerala",
		Aliases:   []string{"malappuram"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"thiruvananthapuram": {
		Name:      "Thiruvananthapuram",
		Latitude:  8.5241,
		Longitude: 76.9366,
		State:     "Kerala",
		Aliases:   []string{"trivandrum", "thiruvananthapuram"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"trivandrum": {
		Name:      "Trivandrum",
		Latitude:  8.5241,
		Longitude: 76.9366,
		State:     "Kerala",
		Aliases:   []string{"trivandrum", "thiruvananthapuram"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"thrissur": {
		Name:      "Thrissur",
		Latitude:  10.5276,
		Longitude: 76.2144,
		State:     "Kerala",
		Aliases:   []string{"trichur", "thrissur"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"hyderabad": {
		Name:      "Hyderabad",
		Latitude:  17.3850,
		Longitude: 78.4867,
		State:     "Telangana",
		Aliases:   []string{"hyderabad"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"vijayawada": {
		Name:      "Vijayawada",
		Latitude:  16.5062,
		Longitude: 80.6480,
		State:     "Andhra Pradesh",
		Aliases:   []string{"vijayawada", "bezawada"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"visakhapatnam": {
		Name:      "Visakhapatnam",
		Latitude:  17.6869,
		Longitude: 83.2185,
		State:     "Andhra Pradesh",
		Aliases:   []string{"vishakhapatnam", "visakhapatnam"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"tirupati": {
		Name:      "Tirupati",
		Latitude:  13.1939,
		Longitude: 79.8245,
		State:     "Andhra Pradesh",
		Aliases:   []string{"tirupati"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"warangal": {
		Name:      "Warangal",
		Latitude:  17.9689,
		Longitude: 78.6294,
		State:     "Telangana",
		Aliases:   []string{"warangal"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"ramagundam": {
		Name:      "Ramagundam",
		Latitude:  18.7627,
		Longitude: 79.4408,
		State:     "Telangana",
		Aliases:   []string{"ramagundam"},
		Verified:  true,
		Source:    "osm-verified",
	},

	// Eastern India
	"kolkata": {
		Name:      "Kolkata",
		Latitude:  22.5726,
		Longitude: 88.3639,
		State:     "West Bengal",
		Aliases:   []string{"calcutta", "kolkata"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"durgapur": {
		Name:      "Durgapur",
		Latitude:  23.8103,
		Longitude: 87.3119,
		State:     "West Bengal",
		Aliases:   []string{"durgapur"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"asansol": {
		Name:      "Asansol",
		Latitude:  23.6838,
		Longitude: 86.9740,
		State:     "West Bengal",
		Aliases:   []string{"asansol"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"siliguri": {
		Name:      "Siliguri",
		Latitude:  26.5124,
		Longitude: 88.4262,
		State:     "West Bengal",
		Aliases:   []string{"siliguri"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"patna": {
		Name:      "Patna",
		Latitude:  25.5941,
		Longitude: 85.1376,
		State:     "Bihar",
		Aliases:   []string{"patna"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"gaya": {
		Name:      "Gaya",
		Latitude:  24.7955,
		Longitude: 84.9994,
		State:     "Bihar",
		Aliases:   []string{"gaya"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"bhagalpur": {
		Name:      "Bhagalpur",
		Latitude:  25.2819,
		Longitude: 86.4730,
		State:     "Bihar",
		Aliases:   []string{"bhagalpur"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"ranchi": {
		Name:      "Ranchi",
		Latitude:  23.3645,
		Longitude: 85.3340,
		State:     "Jharkhand",
		Aliases:   []string{"ranchi"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"dhanbad": {
		Name:      "Dhanbad",
		Latitude:  23.7957,
		Longitude: 86.4304,
		State:     "Jharkhand",
		Aliases:   []string{"dhanbad"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"jamshedpur": {
		Name:      "Jamshedpur",
		Latitude:  22.8046,
		Longitude: 86.1816,
		State:     "Jharkhand",
		Aliases:   []string{"tatanagar", "jamshedpur"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"bhubaneswar": {
		Name:      "Bhubaneswar",
		Latitude:  20.2961,
		Longitude: 85.8245,
		State:     "Odisha",
		Aliases:   []string{"bhubaneswar"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"cuttack": {
		Name:      "Cuttack",
		Latitude:  20.4625,
		Longitude: 85.8830,
		State:     "Odisha",
		Aliases:   []string{"cuttack"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"rourkela": {
		Name:      "Rourkela",
		Latitude:  22.2473,
		Longitude: 84.8533,
		State:     "Odisha",
		Aliases:   []string{"rourkela"},
		Verified:  true,
		Source:    "osm-verified",
	},

	// North-Eastern India
	"guwahati": {
		Name:      "Guwahati",
		Latitude:  26.1445,
		Longitude: 91.7362,
		State:     "Assam",
		Aliases:   []string{"guwahati"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"silchar": {
		Name:      "Silchar",
		Latitude:  24.8170,
		Longitude: 88.6119,
		State:     "Assam",
		Aliases:   []string{"silchar"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"dibrugarh": {
		Name:      "Dibrugarh",
		Latitude:  27.4892,
		Longitude: 94.9142,
		State:     "Assam",
		Aliases:   []string{"dibrugarh"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"imphal": {
		Name:      "Imphal",
		Latitude:  24.8170,
		Longitude: 94.9042,
		State:     "Manipur",
		Aliases:   []string{"imphal"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"shillong": {
		Name:      "Shillong",
		Latitude:  25.5788,
		Longitude: 91.8933,
		State:     "Meghalaya",
		Aliases:   []string{"shillong"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"aizawl": {
		Name:      "Aizawl",
		Latitude:  23.1815,
		Longitude: 92.7325,
		State:     "Mizoram",
		Aliases:   []string{"aizawl"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"agartala": {
		Name:      "Agartala",
		Latitude:  23.8103,
		Longitude: 91.2868,
		State:     "Tripura",
		Aliases:   []string{"agartala"},
		Verified:  true,
		Source:    "osm-verified",
	},

	// Central India
	"chhindwara": {
		Name:      "Chhindwara",
		Latitude:  22.0612,
		Longitude: 78.9497,
		State:     "Madhya Pradesh",
		Aliases:   []string{"chhindwara"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"jabalpur": {
		Name:      "Jabalpur",
		Latitude:  23.1815,
		Longitude: 79.9864,
		State:     "Madhya Pradesh",
		Aliases:   []string{"jabalpur"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"raipur": {
		Name:      "Raipur",
		Latitude:  21.2514,
		Longitude: 81.6296,
		State:     "Chhattisgarh",
		Aliases:   []string{"raipur"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"bilaspur": {
		Name:      "Bilaspur",
		Latitude:  21.7850,
		Longitude: 82.1568,
		State:     "Chhattisgarh",
		Aliases:   []string{"bilaspur"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"durg": {
		Name:      "Durg",
		Latitude:  21.1914,
		Longitude: 81.2776,
		State:     "Chhattisgarh",
		Aliases:   []string{"durg", "bhilai"},
		Verified:  true,
		Source:    "osm-verified",
	},

	// Additional major cities
	"austin": {
		Name:      "Austin",
		Latitude:  23.1291,
		Longitude: 79.9847,
		State:     "Madhya Pradesh",
		Aliases:   []string{"austin"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"allahabad": {
		Name:      "Allahabad",
		Latitude:  25.4358,
		Longitude: 81.8463,
		State:     "Uttar Pradesh",
		Aliases:   []string{"prayagraj", "allahabad"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"varanasi": {
		Name:      "Varanasi",
		Latitude:  25.3176,
		Longitude: 82.9739,
		State:     "Uttar Pradesh",
		Aliases:   []string{"benares", "varanasi"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"meerut": {
		Name:      "Meerut",
		Latitude:  28.9845,
		Longitude: 77.7064,
		State:     "Uttar Pradesh",
		Aliases:   []string{"meerut"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"agra": {
		Name:      "Agra",
		Latitude:  27.1767,
		Longitude: 78.0081,
		State:     "Uttar Pradesh",
		Aliases:   []string{"agra"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"mathura": {
		Name:      "Mathura",
		Latitude:  27.4924,
		Longitude: 77.6737,
		State:     "Uttar Pradesh",
		Aliases:   []string{"mathura"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"bareilly": {
		Name:      "Bareilly",
		Latitude:  28.3670,
		Longitude: 79.4383,
		State:     "Uttar Pradesh",
		Aliases:   []string{"bareilly"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"kanpur": {
		Name:      "Kanpur",
		Latitude:  26.4499,
		Longitude: 80.3319,
		State:     "Uttar Pradesh",
		Aliases:   []string{"cawnpore", "kanpur"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"aligarh": {
		Name:      "Aligarh",
		Latitude:  27.8974,
		Longitude: 77.8981,
		State:     "Uttar Pradesh",
		Aliases:   []string{"aligarh"},
		Verified:  true,
		Source:    "osm-verified",
	},
	"moradabad": {
		Name:      "Moradabad",
		Latitude:  28.8385,
		Longitude: 77.7597,
		State:     "Uttar Pradesh",
		Aliases:   []string{"moradabad"},
		Verified:  true,
		Source:    "osm-verified",
	},
}
