import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#eef2f6' },
  header: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#d9e2ec',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    backgroundColor: '#ffffff',
  },
  brandPill: {
    color: '#0b4a6f',
    fontSize: 10,
    fontWeight: '800',
    letterSpacing: 1,
    marginBottom: 4,
  },
  headerTitle: { fontSize: 21, fontWeight: '800', color: '#0f172a' },
  headerSubtitle: { fontSize: 12, color: '#5b6b7f', marginTop: 2, fontWeight: '600' },
  subtitle: { color: '#607187', marginBottom: 10, fontSize: 14, fontWeight: '600' },
  loginCard: {
    margin: 16,
    padding: 18,
    backgroundColor: '#ffffff',
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#d9e2ec',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.08,
    shadowRadius: 14,
    elevation: 3,
  },
  input: {
    borderWidth: 1,
    borderColor: '#c8d3df',
    borderRadius: 12,
    paddingHorizontal: 12,
    paddingVertical: 12,
    marginBottom: 10,
    backgroundColor: '#fbfdff',
    color: '#0f172a',
    fontSize: 14,
  },
  tabsScroll: {
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#d9e2ec',
    maxHeight: 80,
  },
  tabsWrapContainer: {
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#d9e2ec',
    paddingHorizontal: 10,
    paddingVertical: 10,
  },
  tabs: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 10,
    paddingVertical: 9,
    gap: 8,
  },
  tabsWrap: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    justifyContent: 'space-between',
  },
  tabBtn: {
    paddingHorizontal: 10,
    paddingVertical: 9,
    borderRadius: 22,
    backgroundColor: '#edf2f7',
    borderWidth: 1,
    borderColor: '#dbe5f0',
    minWidth: 94,
  },
  tabBtnCompact: {
    minWidth: 84,
    paddingHorizontal: 8,
    paddingVertical: 8,
  },
  tabBtnGrid: {
    width: '31.5%',
    minWidth: 96,
    borderRadius: 14,
    paddingVertical: 10,
    paddingHorizontal: 8,
  },
  tabBtnActive: { backgroundColor: '#111827', borderColor: '#111827' },
  tabText: { color: '#334155', fontWeight: '700', fontSize: 12, textAlign: 'center' },
  tabTextGrid: { fontSize: 11.5 },
  tabTextCompact: { fontSize: 11 },
  tabTextActive: { color: '#fff', fontWeight: '600', fontSize: 12 },
  content: { padding: 12, gap: 12, paddingBottom: 28 },
  kpiRow: { flexDirection: 'row', gap: 8, marginBottom: 2 },
  kpiRowWrap: { flexWrap: 'wrap' },
  kpiCardPrimary: {
    flex: 1.4,
    backgroundColor: '#0f172a',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    minWidth: 144,
  },
  kpiCardPrimaryWide: {
    width: '100%',
    flexGrow: 0,
    flexBasis: '100%',
  },
  kpiCard: {
    flex: 1,
    backgroundColor: '#ffffff',
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: '#d9e2ec',
    minWidth: 92,
  },
  kpiLabel: { fontSize: 10, fontWeight: '800', letterSpacing: 0.6, color: '#6b7a90' },
  kpiValue: { fontSize: 17, fontWeight: '800', color: '#0f172a', marginTop: 4 },
  kpiLabelLight: { fontSize: 10, fontWeight: '800', letterSpacing: 0.6, color: '#93c5fd' },
  kpiValueLight: { fontSize: 17, fontWeight: '800', color: '#f8fafc', marginTop: 4 },
  sectionTitle: { fontSize: 19, fontWeight: '800', color: '#0f172a' },
  sectionInfo: { fontSize: 13, color: '#56657a', marginBottom: 8, fontWeight: '600' },
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 14,
    borderWidth: 1,
    borderColor: '#d9e2ec',
    shadowColor: '#0f172a',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.05,
    shadowRadius: 10,
    elevation: 2,
  },
  cardTitle: { fontWeight: '800', color: '#1e293b', marginBottom: 5, fontSize: 15 },
  cardMeta: { color: '#5f6f84', marginBottom: 8, fontSize: 13, fontWeight: '500' },
  routeText: {
    fontWeight: '800',
    color: '#1e293b',
    marginBottom: 5,
    fontSize: 15,
  },
  rowActions: { flexDirection: 'row', gap: 8 },
  rowActionsWrap: { flexWrap: 'wrap' },
  infoColumn: { flex: 1, minWidth: 170 },
  primaryBtn: {
    backgroundColor: '#111827',
    paddingVertical: 12,
    alignItems: 'center',
    borderRadius: 12,
  },
  secondaryBtn: {
    borderWidth: 1,
    borderColor: '#d0dbe7',
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 12,
    marginBottom: 10,
    backgroundColor: '#ffffff',
  },
  smallBtn: {
    backgroundColor: '#0f172a',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 10,
    flex: 1,
    minWidth: 110,
    alignItems: 'center',
  },
  smallBtnAlt: {
    backgroundColor: '#eff6ff',
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderRadius: 10,
    flex: 1,
    minWidth: 110,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#dbeafe',
  },
  logoutBtn: {
    backgroundColor: '#ef4444',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 10,
  },
  btnText: { color: '#fff', fontWeight: '800', fontSize: 13 },
  secondaryText: { color: '#1d4ed8', fontWeight: '800', fontSize: 13 },
  helper: { color: '#64748b', fontSize: 12, marginTop: 6, fontWeight: '600' },
  error: { color: '#dc2626', marginTop: 8, fontWeight: '700', fontSize: 13 },
  modalContainer: { flex: 1, backgroundColor: '#eef2f6' },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#d9e2ec',
    backgroundColor: '#fff',
  },
  modalTitle: { fontSize: 18, fontWeight: '700', color: '#0f172a' },
  closeBtn: { fontSize: 24, color: '#64748b', fontWeight: '600' },
  modalContent: { paddingHorizontal: 16, paddingVertical: 16, paddingBottom: 120 },
  sectionBox: {
    backgroundColor: '#fff',
    borderRadius: 14,
    padding: 14,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#d9e2ec',
  },
  sectionLabel: { fontSize: 11, fontWeight: '800', color: '#1e40af', letterSpacing: 0.7, marginBottom: 10 },
  routeBox: {
    paddingVertical: 12,
    paddingHorizontal: 10,
    backgroundColor: '#f3f7fb',
    borderRadius: 8,
    marginBottom: 8,
    alignItems: 'center',
  },
  locationText: { fontSize: 15, fontWeight: '700', color: '#0f172a', marginVertical: 4 },
  routeArrow: { fontSize: 20, color: '#64748b', marginVertical: 4 },
  estimateText: { fontSize: 12, color: '#5e7087', textAlign: 'center', fontWeight: '600' },
  mapPreview: { height: 220, width: '100%', borderRadius: 8 },
  liveMap: { height: 260, width: '100%', borderRadius: 8, marginBottom: 10 },
  detailRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#e8eef5',
  },
  detailKey: { fontSize: 13, color: '#516277', fontWeight: '700' },
  detailValue: { fontSize: 13, color: '#0f172a', fontWeight: '700' },
  totalRow: { borderBottomWidth: 2, borderBottomColor: '#1d4ed8', paddingVertical: 10 },
  totalKey: { fontSize: 14, color: '#0f172a', fontWeight: '700' },
  totalValue: { fontSize: 16, color: '#1d4ed8', fontWeight: '800' },
  actionBox: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 16,
    paddingBottom: 20,
    backgroundColor: '#fff',
    borderTopWidth: 1,
    borderTopColor: '#d9e2ec',
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  actionBtn: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rejectBtn: {
    backgroundColor: '#f1f5f9',
    borderWidth: 1,
    borderColor: '#cbd5e1',
  },
  rejectBtnText: { fontSize: 14, fontWeight: '700', color: '#64748b' },
  acceptBtn: { backgroundColor: '#10b981' },
  acceptBtnText: { fontSize: 14, fontWeight: '700', color: '#fff' },
});
